%include std_string.i

%include LinearMath/btList.i
%include LinearMath/btScalar.i
%include LinearMath/btRandom.i
%include LinearMath/btMinMax.i
%include LinearMath/btVector3.i
%include LinearMath/btQuadWord.i
%include LinearMath/btQuaternion.i
%include LinearMath/btTransform.i
%include LinearMath/btTransformUtil.i
%include LinearMath/btMatrix3x3.i
%include LinearMath/btAabbUtil2.i
%include LinearMath/btAlignedAllocator.i
%include LinearMath/btPoolAllocator.i
%include LinearMath/btQuickprof.i
%include LinearMath/btAlignedObjectArray.i
%include LinearMath/btConvexHull.i
%include LinearMath/btConvexHullComputer.i
%include LinearMath/btMotionState.i
%include LinearMath/btDefaultMotionState.i
%include LinearMath/btGeometryUtil.i
%include LinearMath/btGrahamScan2dConvexHull.i
%include LinearMath/btHashMap.i
%include LinearMath/btIDebugDraw.i
%include LinearMath/btStackAlloc.i
%include LinearMath/btSerializer.i


%include BulletCollision/BroadphaseCollision/btBroadphaseProxy.i
%include BulletCollision/BroadphaseCollision/btBroadphaseInterface.i
%include BulletCollision/BroadphaseCollision/btOverlappingPairCallback.i
%include BulletCollision/BroadphaseCollision/btOverlappingPairCache.i
%include BulletCollision/BroadphaseCollision/btDbvt.i
%include BulletCollision/BroadphaseCollision/btDbvtBroadphase.i
%include BulletCollision/BroadphaseCollision/btAxisSweep3.i
%include BulletCollision/BroadphaseCollision/btCollisionAlgorithm.i
%include BulletCollision/BroadphaseCollision/btDispatcher.i
%include BulletCollision/BroadphaseCollision/btMultiSapBroadphase.i
%include BulletCollision/BroadphaseCollision/btQuantizedBvh.i
%include BulletCollision/BroadphaseCollision/btSimpleBroadphase.i

%include BulletCollision/CollisionShapes/btCollisionShape.i
%include BulletCollision/CollisionShapes/btConvexShape.i
%include BulletCollision/CollisionShapes/btConvexInternalShape.i
%include BulletCollision/CollisionShapes/btPolyhedralConvexShape.i
%include BulletCollision/CollisionShapes/btCollisionMargin.i
%include BulletCollision/CollisionShapes/btBox2dShape.i
%include BulletCollision/CollisionShapes/btBoxShape.i
%include BulletCollision/CollisionShapes/btSphereShape.i
%include BulletCollision/CollisionShapes/btCapsuleShape.i
%include BulletCollision/CollisionShapes/btConeShape.i
%include BulletCollision/CollisionShapes/btCylinderShape.i
%include BulletCollision/CollisionShapes/btCompoundShape.i
%include BulletCollision/CollisionShapes/btStridingMeshInterface.i
%include BulletCollision/CollisionShapes/btConcaveShape.i
%include BulletCollision/CollisionShapes/btConvex2dShape.i
%include BulletCollision/CollisionShapes/btTriangleMeshShape.i
%include BulletCollision/CollisionShapes/btOptimizedBvh.i
%include BulletCollision/CollisionShapes/btTriangleInfoMap.i
%include BulletCollision/CollisionShapes/btBvhTriangleMeshShape.i
%include BulletCollision/CollisionShapes/btConvexHullShape.i
%include BulletCollision/CollisionShapes/btConvexPointCloudShape.i
%include BulletCollision/CollisionShapes/btConvexPolyhedron.i
%include BulletCollision/CollisionShapes/btConvexTriangleMeshShape.i
%include BulletCollision/CollisionShapes/btEmptyShape.i
%include BulletCollision/CollisionShapes/btHeightfieldTerrainShape.i
%include BulletCollision/CollisionShapes/btMaterial.i
%include BulletCollision/CollisionShapes/btMinkowskiSumShape.i
%include BulletCollision/CollisionShapes/btMultiSphereShape.i
%include BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.i
%include BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.i
%include BulletCollision/CollisionShapes/btShapeHull.i
%include BulletCollision/CollisionShapes/btStaticPlaneShape.i
%include BulletCollision/CollisionShapes/btTriangleCallback.i
%include BulletCollision/CollisionShapes/btTriangleBuffer.i
%include BulletCollision/CollisionShapes/btTriangleIndexVertexArray.i
%include BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.i
%include BulletCollision/CollisionShapes/btTriangleShape.i
%include BulletCollision/CollisionShapes/btUniformScalingShape.i

%include BulletCollision/NarrowPhaseCollision/btConvexCast.i
%include BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.i
%include BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.i
%include BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.i
%include BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.i
%include BulletCollision/NarrowPhaseCollision/btGjkConvexCast.i
%include BulletCollision/NarrowPhaseCollision/btGjkEpa2.i
%include BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.i
%include BulletCollision/NarrowPhaseCollision/btGjkPairDetector.i
%include BulletCollision/NarrowPhaseCollision/btManifoldPoint.i
%include BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.i
%include BulletCollision/NarrowPhaseCollision/btPersistentManifold.i
%include BulletCollision/NarrowPhaseCollision/btPointCollector.i
%include BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.i
%include BulletCollision/NarrowPhaseCollision/btRaycastCallback.i
%include BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.i
%include BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.i

%include BulletCollision/CollisionDispatch/SphereTriangleDetector.i
%include BulletCollision/CollisionDispatch/btCollisionObject.i
%include BulletCollision/CollisionDispatch/btCollisionConfiguration.i
%include BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.i
%include BulletCollision/CollisionDispatch/btManifoldResult.i
%include BulletCollision/CollisionDispatch/btCollisionDispatcher.i
%include BulletCollision/CollisionDispatch/btCollisionWorld.i
%include BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btCollisionCreateFunc.i
%include BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btBoxBoxDetector.i

%include BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.i
%include BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.i
%include BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btGhostObject.i
%include BulletCollision/CollisionDispatch/btInternalEdgeUtility.i
%include BulletCollision/CollisionDispatch/btSimulationIslandManager.i
%include BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.i
%include BulletCollision/CollisionDispatch/btUnionFind.i

%include BulletCollision/Gimpact/btBoxCollision.i
%include BulletCollision/Gimpact/btClipPolygon.i
%include BulletCollision/Gimpact/btGeometryOperations.i
%include BulletCollision/Gimpact/btTriangleShapeEx.i
%include BulletCollision/Gimpact/btContactProcessing.i
%include BulletCollision/Gimpact/btGImpactBvh.i
%include BulletCollision/Gimpact/btQuantization.i
%include BulletCollision/Gimpact/btGImpactQuantizedBvh.i
%include BulletCollision/Gimpact/btGImpactShape.i
%include BulletCollision/Gimpact/btGImpactCollisionAlgorithm.i
%include BulletCollision/Gimpact/btGImpactMassUtil.i
%include BulletCollision/Gimpact/btGenericPoolAllocator.i

%include BulletDynamics/ConstraintSolver/btJacobianEntry.i
%include BulletDynamics/ConstraintSolver/btSolverBody.i
%include BulletDynamics/ConstraintSolver/btSolverConstraint.i
%include BulletDynamics/ConstraintSolver/btTypedConstraint.i
%include BulletDynamics/ConstraintSolver/btConeTwistConstraint.i
%include BulletDynamics/ConstraintSolver/btConstraintSolver.i
%include BulletDynamics/ConstraintSolver/btContactConstraint.i
%include BulletDynamics/ConstraintSolver/btContactSolverInfo.i
%include BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.i
%include BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.i
%include BulletDynamics/ConstraintSolver/btHinge2Constraint.i
%include BulletDynamics/ConstraintSolver/btHingeConstraint.i
%include BulletDynamics/ConstraintSolver/btPoint2PointConstraint.i
%include BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.i
%include BulletDynamics/ConstraintSolver/btSliderConstraint.i
%include BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.i
%include BulletDynamics/ConstraintSolver/btUniversalConstraint.i

%include BulletDynamics/Dynamics/btRigidBody.i
%include BulletDynamics/Dynamics/btActionInterface.i
%include BulletDynamics/Dynamics/btDynamicsWorld.i
%include BulletDynamics/Dynamics/btDiscreteDynamicsWorld.i
%include BulletDynamics/Dynamics/btSimpleDynamicsWorld.i

%include BulletDynamics/Vehicle/btVehicleRaycaster.i
%include BulletDynamics/Vehicle/btWheelInfo.i
%include BulletDynamics/Vehicle/btRaycastVehicle.i

%include BulletDynamics/Character/btCharacterControllerInterface.i
%include BulletDynamics/Character/btKinematicCharacterController.i

%include BulletSoftBody/btSoftBodySolvers.i
%include BulletSoftBody/btSoftBodySolverVertexBuffer.i
%include BulletSoftBody/btDefaultSoftBodySolver.i
%include BulletSoftBody/btSoftBody.i
%include BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.i
%include "BulletSoftBody/btSoftBodyData.i"
%include BulletSoftBody/btSoftBodyHelpers.i
%include BulletSoftBody/btSoftBodyInternals.i
%include BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.i
%include BulletSoftBody/btSoftRigidCollisionAlgorithm.i
%include BulletSoftBody/btSoftRigidDynamicsWorld.i
%include BulletSoftBody/btSoftSoftCollisionAlgorithm.i
%include BulletSoftBody/btSparseSDF.i



