require_relative "../../../lib/ruby-bullet"

SWIG = 'swig'
SWIGFLAGS = "-ruby -c++ -w801 #{Ruby::Bullet::Dynamic::get_inc_flags} -I../src/ -autorename"

TARGET = 'bullet_wrap.cpp'

#puts SWIGFLAGS

task :default => "#{TARGET}"

file "#{TARGET}" => "bullet.i" do |t|
  sh "#{SWIG} #{SWIGFLAGS} -o  #{t.name} #{t.prerequisites[0]}"
end

task :clean do
  sh "rm -f #{TARGET}"
end

