SWIG = 'swig'

DEPS_DIR = "../../../deps/"
load "../../../deps/env.rb"


SWIGFLAGS = "-ruby -c++ -w801 #{BULLET_INC} -I../src/ -autorename"

TARGET = 'bullet_wrap.cpp'

#puts SWIGFLAGS

task :default => "#{TARGET}"

file "#{TARGET}" => "bullet.i" do |t|
  sh "#{SWIG} #{SWIGFLAGS} -o  #{t.name} #{t.prerequisites[0]}"
end

task :clean do
  sh "rm -f #{TARGET}"
end

